# 基本は github.com のレポジトリーを指定するだけ
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # カラースキーマ
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'Shougo/unite.vim'
[[plugins]]
repo = 'Shougo/neomru.vim'
[[plugins]]
repo = 'scrooloose/nerdtree'
[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'
